### ISSUE TITLE
incorrect mean / median statistics displayed for z-score wrt selected interval with smoothing

### ISSUE THREAD

**Issue by alee** [openskope/skope-api#20]
From @kintigh

> For a selected area, if I have no smoothing, but I have a transformation of Z-score wrt Selected interval, I get a mean of -2e-17 or effectively zero and a SD of 1 (exactly) as they should.  However, if I add centered or trailing smoothing of any sort it changes the mean and median statistic on the transformed line and for different smoothing I get different means and medians.  As the smoothing is added on top of the transformation, the transformed statistics should not change with the smoothing.  It is curious that the SD does not change but the mean does.  Somehow the wrong years are being grabbed for the mean and statistic.  However, the smoothing does not affect the raw data mean, whether there is a transformation or not (as it should not).  This also does not seem to happen with the moving Z-score or the fixed interval Z score.

Could be a display issue on the UI end but need to look closely at the timeseries service endpoint as well

**Comment by alee** [comment]
Steps to reproduce (example uses lbda dataset)

1. apply "z-score with selected interval" transformation
2. update, note transformed mean / median
3. apply smoothing (centered running average or trailing running average)
4. transformed time series statistics (mean, median, stdev) change for some reason

**Comment by kintigh** [comment]
And check rounding on SD for Original and Transformed (smoothed shows with decimals).
Keith


______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by alee** [comment]
After some more digging & debugging it seems clear this is caused by the timeseries service shifting the temporal ranges when applying smoothing. For example, if the temporal range is [1000, 1200] a smoothing window of 9 will change the bounds to [996, 1204] so that the actual timeseries data shown will still be from 1000-1200. Otherwise when you apply the smoothing it would change to 1004 - 1196. 

The computed summary statistics for the transformed time series use this modified [996, 1204] timeseries slice.

**Comment by kintigh** [comment]
It seems to me that what the app is doing is OK for the smoothed data though I wouldn’t mind it the other way (1004 to 1196 in your example).  Others may have a different idea.  In any event, changing this behavior would probably not fix the problem as the range would be reset in that case too.  However, no matter what, that modified range should not be used for the transformed data.  Interestingly, applying the smoothing does not change the original data stats so it must not be changing the Temporal range.

Here’s an idea.  I think when Calvin originally implemented this the transformation was applied after the smoothing (and that was the order we had on the user interface.  We agreed that this should be done the other way around, so that the transformation was done first. The UI was changed, but I wonder if the implementation when there is both smoothing and transformation is to do the smoothing first which sets the wrong range for the transformed stats.  That would explain some of the behavior, though if that were entirely the case, then one would think that the smoothed data would show in original rather than SD units of the transformed data.

Anyway the transformed data stats need to call the original data range, not the smoothed data range.  Does that make any sense?
Keith


______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by kintigh** [comment]
Actually, thinking about this some more, given what you discovered Allen, why is the smoothed data mean (when not transformed) the same as the actual data mean.  If it is grabbing a different time range, it should be at least slightly different (and that would be correct), but with some experimentation they always appear to be the same (which seems to me problematic) for Paleocar, but not for Palmer Drought Index (for that it changes as it should).

Here is one possible answer.  For Paleocar the mean and median precip seem always to be rounded to the nearest 10 , the GDD to the nearest 100.  We don’t want that rounding, but the above problem may be a rounding issue not a data issue.  (I think we can round these values to the nearest integer.)  The Palmer index and Z-score transformed data are generally rounded to two decimals which seems fine.  We did have an issue with the SD rounding, but you may have fixed that.

Here is a demo of the problem.  There is no way that the smoothed mean is 2600.

***@***.***

Keith
______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501


From: Keith Kintigh
Sent: November 17, 2021 5:51 PM
To: openskope/skope-api ***@***.***>; openskope/skope-api ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [openskope/skope-api] incorrect mean / median statistics displayed for z-score wrt selected interval with smoothing (Issue #20)

It seems to me that what the app is doing is OK for the smoothed data though I wouldn’t mind it the other way (1004 to 1196 in your example).  Others may have a different idea.  In any event, changing this behavior would probably not fix the problem as the range would be reset in that case too.  However, no matter what, that modified range should not be used for the transformed data.  Interestingly, applying the smoothing does not change the original data stats so it must not be changing the Temporal range.

Here’s an idea.  I think when Calvin originally implemented this the transformation was applied after the smoothing (and that was the order we had on the user interface.  We agreed that this should be done the other way around, so that the transformation was done first. The UI was changed, but I wonder if the implementation when there is both smoothing and transformation is to do the smoothing first which sets the wrong range for the transformed stats.  That would explain some of the behavior, though if that were entirely the case, then one would think that the smoothed data would show in original rather than SD units of the transformed data.

Anyway the transformed data stats need to call the original data range, not the smoothed data range.  Does that make any sense?
Keith


______________________________________________________
Keith Kintigh<https://www.public.asu.edu/~kintigh>, Professor Emeritus, Arizona State University<http://asu.edu/> Tempe, USA
Coalition for Archaeological Synthesis<http://archsynth.org/>, Co-President
tDAR<http://tdar.org/> - the Digital Archaeological Record, Co-Chair, Board of Directors
Contact:     505-395-7979(h)     421 Calle Kokopelli, Santa Fe, NM 87501

**Comment by alee** [comment]
I *think* I've fixed the band range issues with respect to the summary statistics. There is still a little bit of weirdness switching between centered and trailing smoothers affecting the transformed time series stats but the original timeseries stats are now fixed to the requested time interval.

@bocinsky and @kintigh can you try different permutations out and see if the stats are more sensible now?
