### ISSUE TITLE
Use a proper geojson parser, like Fiona

### ISSUE THREAD

**Issue by bocinsky** [openskope/skope-api#27]
Currently, many properly formatted geojson files such as those in [openskope/skope-datasets](https://github.com/openskope/skope-datasets/tree/main/geometries) fail to be loaded into the timeseries service. A library such as [Fiona](https://github.com/Toblerity/Fiona) make parsing geojson a snap, and can be integrated directly with rasterio for raster extraction and zonal statistics. For instance, assuming you are in the `datasets` directory on the SKOPE server in the `fiona` Conda environment (which has Fiona and rasterio):

```python
import rasterio
import fiona
from rasterio.mask import raster_geometry_mask
import numpy as np

with fiona.open('https://raw.githubusercontent.com/openskope/skope-datasets/main/geometries/meve.geojson') as meve:
    meve = [feature["geometry"] for feature in meve]

with rasterio.open('paleocar_v2/ppt_water_year/cube.tif') as dataset:
    
    masked, transform, window = raster_geometry_mask(dataset=dataset,
                                                     shapes=meve,
                                                     crop=True,
                                                     all_touched=True)
    
    data = dataset.read(indexes=np.arange(1, dataset.count, 1).tolist(),
                        window=window)
    
    values = np.ma.array(data=data,
                         mask=np.logical_or(np.equal(data, dataset.nodata), masked))
    
    print(
        np.nanmean(values,
                   axis=(1, 2),
                   dtype=np.float64)
    )
#> [652.9346049046321 696.9863760217984 717.9373297002725 ...
#>  592.3732970027248 436.9291553133515 522.4931880108992]
```

**Comment by alee** [comment]
IIUC you're suggesting that we process the `selected_area` parameter in the [timeseries endpoint](https://api.openskope.org/redoc#operation/retrieveTimeseries) using Fiona instead of shapely?

**Comment by bocinsky** [comment]
Yes, though it is not clear to me where the geojson (which is read and displayed on the leaflet map) is parsed into the format used by the timeseries endpoint.

**Comment by alee** [comment]
There's two pathways into the geojson:

1. from a Leaflet layer drawn using the draw toolbar: https://github.com/openskope/skopeui/blob/c73403ef89f88ceb567e7a437b5c4fafbf0af03b/app/components/dataset/Map.vue#L419
2. geojson from a file input that's parsed via `JSON.parse` - there might be a better way to parse this that I haven't found yet but it seems to work as it gets rendered by Leaflet properly on the Map: https://github.com/openskope/skopeui/blob/c73403ef89f88ceb567e7a437b5c4fafbf0af03b/app/components/dataset/Map.vue#L533

**Comment by alee** [comment]
I suspect the issue is how `selected_area` is serialized by [skope-api](https://api.openskope.org/redoc#operation/retrieveTimeseries) automagically by FastAPI into https://github.com/openskope/skope-api/blob/d307a7ff923a1358d39c153dcd1feebc2c415358/timeseries/app/routers/datasets.py#L382

It uses some magic type conversion and [geojson-pydantic](https://github.com/developmentseed/geojson-pydantic) to generate a [Point](https://github.com/openskope/skope-api/blob/d307a7ff923a1358d39c153dcd1feebc2c415358/timeseries/app/routers/datasets.py#L57) or [Polygon](https://github.com/openskope/skope-api/blob/d307a7ff923a1358d39c153dcd1feebc2c415358/timeseries/app/routers/datasets.py#L102) given the incoming text data that's picked up by the `retrieveTimeSeries` endpoint
